# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'BrainyRL' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BrainyRL
  pod 'SwiftLint'

  target 'BrainyRLTests' do
    # Pods for testing
  end

end
